4finance/micro-infra-spring

- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/common/request/HttpMethod.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/common/response/receive/MethodParamsApplier.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/common/response/receive/MethodParamsApplierSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/get/GetHttpMethodBuilderSpec.groovy
Idea: maybe we should treat fixed URLs as template with no arguments? This can potentially simplify implementation.
> Treat GString with variables same as onUrlFromTemplate in ServiceRestClient. Closes #148

- build.gradle
- micro-infra-spring-config/build.gradle
... and Spring to 4.1.4.RELEASE.
It fixes issue with centralized properties management on Windows.
By the way it removes duplication in dependency management (related change in [micro-common-release](https://github.com/4finance/micro-common-release/pull/11)).
> Upgrade Spring Cloud to 1.0.0.RC1, Spring Boot to 1.2.1.RELEASE

- micro-deps/README.md
- micro-deps/micro-deps/README.md
- stub-runner/stub-runner-spring/README.md
- stub-runner/stub-runner/README.md
> [#203] Removing redundant buttons in child readmes, fixing broken links

- micro-infra-camel/src/main/groovy/com/ofg/infrastructure/camel/CorrelationIdInterceptor.groovy
- micro-infra-camel/src/main/groovy/com/ofg/infrastructure/camel/CorrelationIdOnCamelRouteConfiguration.groovy
- micro-infra-camel/src/main/groovy/com/ofg/infrastructure/camel/aspects/CorrelationIdOnCamelRouteAspect.groovy
- micro-infra-camel/src/test/groovy/com/ofg/infrastructure/camel/AcceptanceSpec.groovy
- micro-infra-camel/src/test/groovy/com/ofg/infrastructure/camel/CorrelationIdInterceptorSpec.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/correlationid/UuidGenerator.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/scheduling/ScheduledTaskWithCorrelationIdAspect.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/scheduling/TaskSchedulingConfiguration.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/correlationid/CorrelationIdConfiguration.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/correlationid/CorrelationIdFilter.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/scheduling/CorrelationIdOnScheduledMethodSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/correlationid/CorrelationIdFilterSkipPatternTest.groovy
> Avoid UUID generation duplication

- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/HttpMethodBuilder.groovy
> JavaDocs for retryUsing

- CONTRIBUTING.md
I would prefer to do the same form GUI with just another checkbox.
> Add suggestion to request simple merging from GUI

- micro-infra-spring-config/src/main/java/com/ofg/infrastructure/property/ConfigLocations.java
- micro-infra-spring-config/src/main/java/com/ofg/infrastructure/property/FileSystemPoller.java
It fixes https://github.com/4finance/micro-infra-spring/issues/280
> [#280] FileSystemPoller warns when one of config dirs is missing

- micro-deps/micro-deps-spring-config/src/main/groovy/com/ofg/infrastructure/discovery/ServiceDiscoveryInfrastructureConfiguration.groovy
Make sure application registers itself and with correct name
> Log name and address which we register in ZooKeeper on startup.

- micro-deps/build.gradle
Due to clashing Spock versions.
> Workaround for problem with running tests from Idea

- micro-infra-spring-config/src/main/java/com/ofg/infrastructure/property/AppCoordinates.java
- micro-infra-spring-config/src/main/java/com/ofg/infrastructure/property/ConfigLocations.java
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/AppCoordinatesSpec.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/ConfigLocationsSpec.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/FileSystemPollerSpec.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/LoadingFromFileSystemSpec.groovy
- micro-infra-spring-config/src/test/resources/test-config-dir/common/com/ofg/micro-app.properties
- micro-infra-spring-config/src/test/resources/test-config-dir/common/com/ofg/micro-app.yaml
- micro-infra-spring-config/src/test/resources/test-config-dir/common/com/ofg/pl/micro-app-pl.properties
- micro-infra-spring-config/src/test/resources/test-config-dir/common/com/ofg/pl/micro-app-pl.yaml
- micro-infra-spring-config/src/test/resources/test-config-dir/common/global.properties
- micro-infra-spring-config/src/test/resources/test-config-dir/common/global.yaml
- micro-infra-spring-config/src/test/resources/test-config-dir/prod/com/ofg/micro-app.properties
- micro-infra-spring-config/src/test/resources/test-config-dir/prod/com/ofg/micro-app.yaml
- micro-infra-spring-config/src/test/resources/test-config-dir/prod/com/ofg/pl/micro-app-pl.properties
- micro-infra-spring-config/src/test/resources/test-config-dir/prod/com/ofg/pl/micro-app-pl.yaml
ConfigLocations was also refactored. It could create less File objects, but it is called only at the beginning, so IMHO it is not an issue and a code is more readable.
Wiki(s) should be updated after merge.
> Shared properties across all microservices

- micro-infra-spring-config/build.gradle
- micro-infra-spring-config/src/main/java/com/ofg/infrastructure/property/FileSystemLocator.java
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/LoadingFromInvalidFileSpec.groovy
- micro-infra-spring-config/src/test/resources/microservice-invalid.json
- micro-infra-spring-config/src/test/resources/test-config-dir/prod/io/invalid-app.yaml
By the way it fixes #309.
Done together with @dst
> Upgrade Spring Cloud and Spring RSA to 1.0.0.RELEASE

- build.gradle
To verify that micro-common-release 0.1.17 really works :)
> Upgrade micro-common-release to 0.1.17

- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/correlationid/CorrelationIdUpdater.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/correlationid/CorrelationIdUpdaterSpec.groovy
Before only one parameter was supported. In addition tests were enhanced.
> Support for passing multiple parameters in wrapClosureWithId(Closure)

- micro-deps/micro-deps-spring-config/src/main/groovy/com/ofg/config/BasicProfiles.groovy
Add smokeTests profile to mock third party services.
> Add smokeTests profile to mock third party services.

- build.gradle
- micro-infra-camel/build.gradle
- micro-infra-spring-base/build.gradle
- micro-infra-spring-reactor/build.gradle
- stub-runner/stub-runner/build.gradle
- swagger/micro-infra-spring-swagger/build.gradle
Spring boot to 1.2.3, Spring to 4.1.6 and Camel, Metrics, Hystrix, Spring Reactor, Logback, Swagger, Slf4j, Jackson, AspectJ, Curator.
> Massive dependencies upgrade

- .travis.yml
- gradle.properties
@szpak, @marcingrzejszczak please ~~review~~ merge ;)
> enable gradle daemon and parallel build by default

- micro-infra-spring-base/src/main/java/com/ofg/infrastructure/environment/EnvironmentSetupVerifier.java
> DefaultGroovyMethods removed after converting to java

- .travis.yml
To prevent issues like [that](https://travis-ci.org/4finance/micro-infra-spring/jobs/59867778#L3761).
> Disable --continue in release command

- stub-runner/stub-runner/src/main/groovy/com/ofg/stub/StubDownloader.groovy
> Log information about downloading stub-definitions

- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/UrlUtils.java
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/common/response/receive/HttpEntitySending.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/delete/DeleteMethodBuilder.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/get/GetMethodBuilder.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/head/HeadMethodBuilder.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/options/OptionsMethodBuilder.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/post/PostMethodBuilder.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/put/PutMethodBuilder.groovy
- micro-infra-spring-base/src/main/java/com/ofg/infrastructure/web/resttemplate/fluent/UrlUtils.java
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/UrlUtilsSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/delete/DeleteHttpMethodBuilderSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/get/GetHttpMethodBuilderSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/head/HeadHttpMethodBuilderSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/options/OptionsHttpMethodBuilderSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/post/PostHttpMethodBuilderSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/put/PutHttpMethodBuilderSpec.groovy
I want to add simple mechanism to add query parameters to URL.
> Query parameters

- micro-deps/micro-deps-spring-config/src/main/java/com/ofg/infrastructure/discovery/AddressProviderConfiguration.java
- micro-deps/micro-deps-spring-config/src/test/groovy/com/ofg/infrastructure/discovery/ServiceResolverConfigurationSpec.groovy
This reverts commit 1cf0c620e3dfa97a66fb0b7f2e5f66cb2dea70af.
We do not need random port in lib. We can change this by configuration not in code.
> Revert "Choose random port if not set to prevent port clash"

- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/ServiceRestClientConfigurationSupport.groovy
> Rename retry.threads property to rest.client.retry.threads

- micro-deps/micro-deps/src/main/java/com/ofg/infrastructure/discovery/ServiceResolver.java
- micro-deps/micro-deps/src/main/java/com/ofg/infrastructure/discovery/StubbedServiceResolver.java
- micro-deps/micro-deps/src/main/java/com/ofg/infrastructure/discovery/ZookeeperServiceResolver.java
- micro-deps/micro-deps/src/test/groovy/com/ofg/infrastructure/discovery/MicroDepsServiceSpec.groovy
> Use ServiceAlias instead of String when querying by alias

- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/correlationid/CorrelationIdUpdater.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/correlationid/CorrelationIdAspect.java
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/correlationid/CorrelationIdAspectSpec.groovy
correlationId propagation fix when using WebAsyncTask
> correlationId propagation for WebAsyncTask

- build.gradle
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/correlationid/CorrelationIdAspect.java
This should resolve all problem with latest and greatest accurest
> wiremock update to 2.x

- gradle/runBootMicroserviceAcceptanceTests.sh
Goes with: https://github.com/4finance/boot-microservice/commit/475dd4c28c5eaa9674bc85b555b8786cd5aef272#diff-0f59d9cd4fa6fc342c0a5e459a1cf1f4R14
> Added uptodate check in Travis

- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/correlationid/CorrelationIdUpdaterSpec.groovy
A reminiscence of the latest Warsaw Groovy User Group meeting :).
> Simplify tests with Callable

- build.gradle
Update spring boot to 1.3.0.RELEASE
> Spring boot update

- micro-infra-spring-config/src/main/java/com/ofg/infrastructure/property/SystemPropertiesOverridingPropertySourceLocator.java
- micro-infra-spring-config/src/main/resources/META-INF/spring.factories
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/BootstrapPropertySourceOverrideSpec.groovy
Fixes #457
This change overrides spring cloud config to fix this issue
> Prioritize system properties over bootstrap

- micro-infra-spring-config/src/main/java/com/ofg/infrastructure/property/FileSystemLocator.java
> [#553] Fix hardcoded environment

- micro-infra-spring-base/src/main/java/com/ofg/infrastructure/tracing/TracingConfiguration.java
- micro-infra-spring-base/src/main/resources/META-INF/spring.factories
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/base/BaseConfiguration.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/correlationid/CorrelationIdAsyncSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/RestOperationsMetricsAspectIntegrationSpec.groovy
- micro-infra-spring-config/src/main/groovy/com/ofg/infrastructure/property/LogbackConfiguration.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/LogbackConfigurationSpec.groovy
> Changes in tracing capabilities and logging

- micro-infra-spring-base/src/main/java/com/ofg/infrastructure/web/logging/HttpDataExtractor.java
Simple fix for logging & obfuscating mechanism ... handling no content response
> 542 fix for extract response with no content

- micro-infra-spring-base/src/main/java/com/ofg/infrastructure/web/logging/FeignCallObfuscatingLogger.java
> fix binary data copying

- build.gradle
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/logging/feign/FeignRequestResponseLoggingConifguration.java
- micro-infra-spring-base/src/main/java/com/ofg/infrastructure/web/logging/FeignCallObfuscatingLogger.java
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/logging/FeignCallObfuscatingLoggerSpec.groovy
> Do not convert bytes to String, when obfuscating response

- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/healthcheck/CollaboratorsConnectivityController.java
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/healthcheck/CollaboratorsStatusResolver.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/healthcheck/CollaboratorsConnectivityControllerSpec.groovy
> ping in collaborators controller

- stub-runner/stub-runner/src/main/groovy/com/ofg/stub/mapping/StubRepository.groovy
- stub-runner/stub-runner/src/test/groovy/com/ofg/stub/mapping/StubRepositorySpec.groovy
- stub-runner/stub-runner/src/test/resources/deepenMappingsRepository/deeper/located/mappings/com/ofg/bye/admin/admin.json
- stub-runner/stub-runner/src/test/resources/deepenMappingsRepository/deeper/located/mappings/com/ofg/bye/bye.json
- stub-runner/stub-runner/src/test/resources/deepenMappingsRepository/deeper/located/mappings/com/ofg/ping/ping.json
- stub-runner/stub-runner/src/test/resources/deepenMappingsRepository/deeper/located/mappings/pl/com/ofg/bye/pl_bye.json
- stub-runner/stub-runner/src/test/resources/deepenMappingsRepository/deeper/located/mappings/pl/com/ofg/bye/pl_overridden_bye.json
> Weakening subs repository layout restrictions (#615)

- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/discovery/ZookeeperDependencyStubsConfigurationFix.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/discovery/ZookeeperDependencyStubsConfigurationFixSpec.groovy
Workaround for bug in spring-cloud-zookeeper: https://github.com/spring-cloud/spring-cloud-zookeeper/issues/138
> Fix for wrongly created stubs configuration

- micro-infra-spring-base/src/main/resources/META-INF/spring.factories
Required by https://github.com/4finance/micro-infra-spring/pull/626
> Add stub configuration fix to spring factories

- stub-runner/stub-runner/src/main/groovy/com/ofg/stub/CollaboratorsPathResolver.groovy
We have a problem when instance is null, see the log:
```
14:16:54.944 [Curator-ServiceCache-0] DEBUG com.ofg.stub.CollaboratorsPathResolver - Service cache changed
14:16:54.944 [Curator-ServiceCache-0] DEBUG com.ofg.stub.CollaboratorsPathResolver - Service provider returned instance: null
```
+ refactoring to close resources after they aren't needed
> Use service cache to extract instance in the listener

- micro-deps/micro-deps-spring-test-config/src/main/groovy/com/ofg/infrastructure/stub/Stub.groovy
- micro-deps/micro-deps-spring-test-config/src/test/groovy/com/ofg/infrastructure/stub/StubSpec.groovy
This reverts commit cffc3c351a513f44cf3daa42a791b41b7dd6bf14.
This reverts https://github.com/4finance/micro-infra-spring/pull/637
The idea was soooo wrong...
> Revert "Allows to register mapping for stub"

- build.gradle
See [Spring Cloud Edgware Release Notes](https://github.com/spring-projects/spring-cloud/wiki/Spring-Cloud-Edgware-Release-Notes).
> Spring Cloud Edgware.SR1
