- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/view/PrettyPrintingInDevelopmentEnvironmentSpec.groovy
Depending on platform and git configuration this test is failing because of different EOL symbol.
Just parse String into lines (using CR/LF-friendly BufferedReader underneath) and compare them one after another.
> Ignore CR/LF differences entirely in test

- swagger/micro-infra-spring-swagger/src/main/groovy/com/ofg/infrastructure/web/swagger/SwaggerConfiguration.groovy
Apparently this bug surfaced only after upgrade from Spring Boot 1.1.8 to 1.1.9
Fixes #157
> addResourceLocations() takes paths, not patterns as per JavaDoc

- micro-deps/micro-deps-spring-test-config/src/main/groovy/com/ofg/infrastructure/discovery/web/MockServerConfiguration.groovy
In order to be able write integration tests, that directly extends MvcWiremockIntegrationTest I have added an instance of PropertySourcesPlaceholderConfigurer bean to the context initiated by this tests. It enables Spring to evaluate SPEL in MockServerConfiguration.httpMockServer method.
> PropertySourcesPlaceholderConfigurer bean added to context defined in MockServerConfiguration

- micro-deps/build.gradle
To prevent transition dependency in end projects to SNAPSHOT version.
> Downgrade Spock to 0.7 in micro-deps-spring-test-config

- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/decrypt/DecryptingPropertyExtendedTest.groovy
These tests are passing since 6f8ee97da7599cdfbf9a213f6350f5016c260556 (see: #97).
> Un-ignoring tests, working after upgrade to Spring Cloud M3

- stub-runner/stub-runner-spring/src/main/groovy/com/ofg/stub/StubDownloader.groovy
Regression in 0.8.8. Can be misleading for end users.
> [#272] stub-runner should not fail completely on local repository

- micro-infra-spring-config/src/main/java/com/ofg/infrastructure/property/AppCoordinates.java
- micro-infra-spring-config/src/main/java/com/ofg/infrastructure/property/ConfigLocations.java
- micro-infra-spring-config/src/main/java/com/ofg/infrastructure/property/FileSystemLocator.java
- micro-infra-spring-config/src/main/java/com/ofg/infrastructure/property/FileSystemPoller.java
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/AppCoordinatesTest.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/ConfigLocationsTest.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/FileSystemPollerTest.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/LoadingFromFileSystemTest.groovy
- micro-infra-spring-config/src/test/resources/microservice-enc.json
- micro-infra-spring-config/src/test/resources/test-config-dir/common/com/ofg/micro-app.properties
- micro-infra-spring-config/src/test/resources/test-config-dir/common/com/ofg/micro-app.yaml
- micro-infra-spring-config/src/test/resources/test-config-dir/prod/com/ofg/micro-app.properties
- micro-infra-spring-config/src/test/resources/test-config-dir/prod/com/ofg/micro-app.yaml
- micro-infra-spring-config/src/test/resources/test-config-dir/prod/com/ofg/pl/micro-app-pl.properties
- micro-infra-spring-config/src/test/resources/test-config-dir/prod/com/ofg/pl/micro-app-pl.yaml
This pull request introduces a new configuration location called `common`. This configuration can be shared across all envirenments. `common` dir is located next to dev, test or prod and has lowest priority (comparing with env and country locations).
Additionally a bug in FileSystemPoller was fixed. It took into account only changes in an env location and ignored changes in a country location. Now poller watches common, env and country locations.
Example configuration files were adjusted to cover in test different scenarios with priorities.
Tiny refactorings were introduced as well.
> Shared properties across environments

- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/correlationid/CorrelationIdUpdaterSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/hystrix/CorrelatedCommandSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/correlationid/CorrelationIdFilterSkipPatternSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/custom/InputStreamPrinterSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/common/response/executor/RestExecutorSpec.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/AbstractIntegrationSpec.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/AppCoordinatesSpec.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/ConfigLocationsSpec.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/FileSystemPollerSpec.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/LoadingFromFileSystemSpec.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/decrypt/BrokenJceInstallationSpec.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/decrypt/DecryptingPropertyExtendedSpec.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/decrypt/DecryptingPropertySpec.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/decrypt/LoadingEncryptedFromFileSystemSpec.groovy
The majority of our Spock specifications has `Spec` suffix in name, so let's be consistent with all specifications.
> Use Spec suffix in Spock specifications

- micro-infra-camel/build.gradle
- micro-infra-camel/src/test/groovy/com/ofg/infrastructure/camel/AcceptanceSpec.groovy
We was making ConcurrencyModificationException due to fact changes made in function removeRouteDefinitions - removing didn't change results
> [#150] Upgraded Camel version 

- build.gradle
- micro-infra-spring-base/build.gradle
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/hystrix/CircuitBreakers.groovy
Also Spring Framework upgraded to 4.1.5 (needed by Spring Boot).
**Inportant notes**. Spring 4.1.5 is minimal required versions to not fail in runtime (due to [that](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.java#L434). It should be put into release notes.
> Upgrade Spring Boot to 1.2.2 and Hystrix to 1.4.0-rc.9

- build.gradle
- stub-runner/stub-runner/build.gradle
To be compatible with tomcat-embed 8.0.20 used by spring-boot 1.2.2.
Fixes #334
> [#334] Update servlet-api to 3.1.0

- micro-infra-spring/src/main/java/com/ofg/infrastructure/config/EnableMicroserviceDocumentation.java
- micro-infra-spring/src/main/java/com/ofg/infrastructure/config/SwaggerDocumentationConfiguration.java
`SwaggerConfiguration` and `@EnableMicroserviceDocumentation` should be enough, imo third way to do the same is not needed.
> deprecate SwaggerDocumentationConfiguration

- .travis.yml
- gradle.properties
- stub-runner/stub-runner/build.gradle
The artifact has different artifactId to not override original
(not fatjar) artifact in jcenter. To not additionally complicate
build script the new fatjar has still fatjar classifier (which is
redundant).
> [#372] Ability to deploy stub-runner fatjar to separate repo

- build.gradle
To make it easier to distinguish release and not release tags. Useful when manually releasing stub-runner fatjar from CI.
> Change released tag format

- build.gradle
Java 8u25 with too strict backward branch verification fix is more than half-year-old
> remove noverify JVM flag

- build.gradle
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/correlationid/CorrelationIdAspectSpec.groovy
Groovy 2.4.3 does not like twofold nested classes. Will be reported later as a repression in Groovy.
Fixes #374.
> [#374] Upgrade to Groovy 2.4.3

- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/healthcheck/CollaboratorsConfiguration.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/healthcheck/CollaboratorsConnectivityController.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/healthcheck/CollaboratorsStatusResolver.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/healthcheck/CollaboratorsConnectivityControllerSpec.groovy
This PR is purely extracting of some functionality from `CollaboratorsConnectivityController` into a separate class so that it can be reused without Spring MVC.
> Extracting collaborators to allow easier integration in legacy applications

- micro-deps/micro-deps-spring-config/src/main/java/com/ofg/infrastructure/discovery/AddressProviderConfiguration.java
- micro-deps/micro-deps-spring-config/src/test/groovy/com/ofg/infrastructure/discovery/ServiceResolverConfigurationSpec.groovy
We should not use default port because it will clash with port that was already bind or with other instance during build on build server
> Choose random port if not set to prevent port clash

- micro-deps/micro-deps/src/main/java/com/ofg/infrastructure/discovery/util/ProviderStrategyFactory.java
because they are stateful, e.g.: `private final AtomicReference<ServiceInstance<T>>   ourInstance = new AtomicReference<ServiceInstance<T>>(null);`
> Provider strategies should not be constant

- build.gradle
- micro-deps/build.gradle
- micro-infra-spring-base/build.gradle
- micro-infra-spring-config/build.gradle
- micro-infra-spring-test/build.gradle
- settings.gradle
- stub-runner/stub-runner-spring/build.gradle
- stub-runner/stub-runner/README.md
- stub-runner/stub-runner/build.gradle
By the way duplicated module names were changed to prevent StackOverflowException in Sonar.
It will be required to adjust all scripts/jobs/etc. which call stub-runner or micro-deps tasks directly.
> [#313] Add Sonarqube plugin

- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/correlationid/CorrelationIdConfiguration.java
Was fixed in https://github.com/4finance/micro-infra-spring/commit/e403c7e390c6c65646cb3ed8dfd23b2968115e8a but broken again in https://github.com/4finance/micro-infra-spring/commit/0ec2c3fc273c454d00be9bc574019dcbcd5ac537
> Broken condition when filtering out static resource for correlation ID generation

- build.gradle
Could not resolve all dependencies for configuration ':micro-infra-spring-reactor:compile'.
> Could not find org.projectreactor:reactor-spring:1.0.1.RELEASE.
Searched in the following locations:
file:/root/.m2/repository/org/projectreactor/reactor-spring/1.0.1.RELEASE/reactor-spring-1.0.1.RELEASE.pom
file:/root/.m2/repository/org/projectreactor/reactor-spring/1.0.1.RELEASE/reactor-spring-1.0.1.RELEASE.jar
https://jcenter.bintray.com/org/projectreactor/reactor-spring/1.0.1.RELEASE/reactor-spring-1.0.1.RELEASE.pom
https://jcenter.bintray.com/org/projectreactor/reactor-spring/1.0.1.RELEASE/reactor-spring-1.0.1.RELEASE.jar
Required by:
com.ofg:micro-infra-spring-reactor:0.9.1
> added maven central for repos

- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/common/response/executor/ResponseTypeRelatedRequestsExecutor.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/common/response/receive/BodyContainingWithQueryParameters.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/common/response/receive/BodylessWithQueryParameters.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/common/response/receive/ParametersHaving.java
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/common/response/receive/QueryParametersHaving.java
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/common/response/receive/ResponseReceiving.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/delete/DeleteMethodBuilder.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/get/GetMethodBuilder.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/head/HeadMethodBuilder.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/options/OptionsMethodBuilder.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/post/PostMethodBuilder.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/put/PutMethodBuilder.groovy
- micro-infra-spring-base/src/main/java/com/ofg/infrastructure/web/resttemplate/fluent/UrlUtils.java
- micro-infra-spring-base/src/main/java/com/ofg/infrastructure/web/resttemplate/fluent/common/response/receive/ParametersSetting.java
- micro-infra-spring-base/src/main/java/com/ofg/infrastructure/web/resttemplate/fluent/common/response/receive/QueryParametersSetting.java
- micro-infra-spring-base/src/main/java/com/ofg/infrastructure/web/resttemplate/fluent/common/response/receive/WithQueryParameters.java
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/UrlUtilsSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/delete/DeleteHttpMethodBuilderSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/get/GetHttpMethodBuilderSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/head/HeadHttpMethodBuilderSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/options/OptionsHttpMethodBuilderSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/post/PostHttpMethodBuilderSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/put/PutHttpMethodBuilderSpec.groovy
Parameters should not contain assignment (equals sign) in case of empty or null values.
"?param is valid"
> Better http query parameters according to discussion on issue #469 

- micro-infra-spring-config/src/main/ruby/aes.rb
aes.rb -d can accept encrypted secrets with and without prefix, previously it was crashing with prefix
> When decrypting, {cipher} prefix is optionally allowed

- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/correlationid/CorrelationIdUpdater.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/correlationid/CorrelationIdUpdaterSpec.groovy
If thread has no correlation ID attached, after calling withId() this explicit CID remains
This happens because during cleanup we call updateCorrelationId(null), which does nothing rather than cleaning up. CC: @cameleeck, @uchoromanska.
> Correlation ID passed to CorrelationIdUpdater.withId() is not cleaned afterwards

- stub-runner/stub-runner/src/main/groovy/com/ofg/stub/StubRunnerMain.groovy
Fix: Default option handler don't allow values for boolean options. It was not possible to pass false value.
> useMicroserviceDefinitions - allow false value by passing argument

- build.gradle
- micro-deps/build.gradle
Which fixes Spock mocking issue when Java 8 is used (like this: https://groups.google.com/forum/#!topic/spockframework/59WIHGgcSNE).
Fixes #547.
> [#547] Upgrade cglib to 3.2.0

- build.gradle
vcsUrl is one of the mandatory parameters according to docs
[gradle-bintray-plugin](https://github.com/bintray/gradle-bintray-plugin/blob/master/README.md)
> fix missing vcsUrl in bintray upload

- build.gradle
- micro-deps/build.gradle
- micro-deps/micro-deps-spring-config/src/test/groovy/com/ofg/infrastructure/discovery/ZookeeperConnectorConditionsSpec.groovy
- micro-deps/micro-deps/src/test/groovy/com/ofg/infrastructure/discovery/ServiceConfigurationResolverSpec.groovy
- micro-deps/micro-deps/src/test/groovy/com/ofg/infrastructure/discovery/ServicePathSpec.groovy
- micro-deps/micro-deps/src/test/groovy/com/ofg/infrastructure/discovery/util/LoadBalancerTypeSpec.groovy
- micro-deps/micro-deps/src/test/groovy/com/ofg/infrastructure/discovery/util/ProviderStrategyFactorySpec.groovy
- micro-infra-camel/build.gradle
- micro-infra-spring-base/build.gradle
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/environment/EnvironmentSetupVerifierSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/healthcheck/PingClientTest.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/metrics/config/GraphitePublisherRegistrationSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/tracing/TracingPropertiesEnablerSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/correlationid/CorrelationIdAspectSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/RegexMatchingPathElidingURIMetricNamerSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/custom/HttpStatusVerifierSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/custom/InputStreamPrinterSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/HTTPAuthorizationUtilsSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/UrlUtilsSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/common/response/executor/UrlParsingUtilsSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/headers/HeadersSettingSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/view/DisablingJsonGeneratorFeaturesSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/view/DisablingJsonParserFeaturesSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/view/EnablingJsonGeneratorFeaturesSpec.groovy
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/view/EnablingJsonParserFeaturesSpec.groovy
- micro-infra-spring-config/build.gradle
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/AppCoordinatesSpec.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/FileSystemPollerSpec.groovy
- stub-runner/stub-runner-spring/build.gradle
- stub-runner/stub-runner/build.gradle
No more `@Unroll` just to enable parameterized tests unrolling :).
As a result number of tests increased from 483 to 497. Probably there was `@Unroll` annotation missing in some places.
By the way the aggregated testReport task was added.
> Simplify parametrized tests with spock-global-unroll

- micro-deps/build.gradle
Adding rxjava as a dependency to not fail if someone didn't have it imported in his project
> Adding rxjava as a dependency

- micro-infra-spring-base/src/main/java/com/ofg/infrastructure/metrics/config/MetricsConfiguration.java
This PR provides a way to disable metrics configuration with `-Dmetrics.enabled=false` or a Spring property.
The property is not very unique, but I wanted to consistent with other related properties.
Fixes #551.
> [#551] Ability to disabled metrics configuration

- micro-deps/micro-deps-spring-config/src/main/java/com/ofg/infrastructure/discovery/ServiceDiscoveryInfrastructureConfiguration.java
- micro-deps/micro-deps-spring-config/src/test/groovy/com/ofg/infrastructure/discovery/ServiceResolverSpec.groovy
- micro-deps/micro-deps/src/main/java/com/ofg/infrastructure/discovery/ZookeeperServiceResolver.java
- micro-deps/micro-deps/src/main/java/com/ofg/infrastructure/discovery/util/MicroDepsService.java
- micro-deps/micro-deps/src/test/groovy/com/ofg/infrastructure/base/SpecWithZookeper.groovy
- micro-deps/micro-deps/src/test/groovy/com/ofg/infrastructure/discovery/IgnorePayloadInstanceSerializerSpec.groovy
- stub-runner/stub-runner/src/main/groovy/com/ofg/stub/CollaboratorsPathResolver.groovy
- stub-runner/stub-runner/src/main/groovy/com/ofg/stub/registry/StubRegistry.groovy
- stub-runner/stub-runner/src/test/groovy/com/ofg/stub/ProjectMetadataResolverSpec.groovy
Map-based instead of Void-based serialization to allow parsing non-null payloads.
Handles null uriSpec with a sensible default (into a @Deprecated implementation though), please review if still relevant
> More tolerance on: - non-null payload - missing uriSpec

- micro-deps/micro-deps-spring-config/src/main/java/com/ofg/infrastructure/discovery/ZookeeperServiceResolverConfiguration.java
When using
@SpringBootTest(webEnvironment = RANDOM_PORT)
server.port is set to 0
which ends up with 
IllegalStateException("Cannot create instance whose port is not greater than 0")
when creating ZookeeperServiceDiscovery bean
> randomize port when server.port is set to 0

- micro-deps/build.gradle
- micro-deps/micro-deps-spring-config/src/main/java/com/ofg/infrastructure/discovery/SpringCloudToMicroserviceJsonConverter.java
- micro-deps/micro-deps-spring-config/src/test/groovy/com/ofg/infrastructure/discovery/SpringCloudToMicroserviceJsonConverterSpec.groovy
Currently spring cloud allows for definition of custom stubs, but microservice.json converter doesn't take advantage of this functionality. Instead it builds stubs from servicePath.
This causes (among other issues) the standalone stub-runner to retrieve erroneous stub paths if custom stubs are defined.
> fix for spring-cloud to microservice.json converter not using stubs

- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/logging/feign/FeignRequestResponseLoggingConifguration.java
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/logging/feign/SleuthRequestIdProvider.java
- micro-infra-spring-base/src/main/java/com/ofg/infrastructure/web/logging/FeignCallObfuscatingLogger.java
- micro-infra-spring-base/src/main/java/com/ofg/infrastructure/web/logging/RequestDataProvider.java
- micro-infra-spring-base/src/main/java/com/ofg/infrastructure/web/logging/RequestIdProvider.java
- micro-infra-spring-base/src/main/java/com/ofg/infrastructure/web/logging/SpanIdProvider.java
- micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/logging/FeignCallObfuscatingLoggerSpec.groovy
when attempting to obfuscate response log, if response cannot be matched to its originating request, logging is skipped
> bugfix for logging obfuscated response

- stub-runner/stub-runner/src/main/groovy/com/ofg/stub/mapping/StubRepository.groovy
- stub-runner/stub-runner/src/test/groovy/com/ofg/stub/mapping/StubRepositorySpec.groovy
- stub-runner/stub-runner/src/test/resources/deepenMappingsRepository/deeper/located/mappings/com/ofg/bye/admin/admin.json
- stub-runner/stub-runner/src/test/resources/deepenMappingsRepository/deeper/located/mappings/com/ofg/bye/bye.json
- stub-runner/stub-runner/src/test/resources/deepenMappingsRepository/deeper/located/mappings/com/ofg/ping/ping.json
- stub-runner/stub-runner/src/test/resources/deepenMappingsRepository/deeper/located/mappings/pl/com/ofg/bye/pl_bye.json
- stub-runner/stub-runner/src/test/resources/deepenMappingsRepository/deeper/located/mappings/pl/com/ofg/bye/pl_overridden_bye.json
Having mapping folder located directly under repositoryRoot can cause that stubs aren't found.
This happens when using SpringCloudContractVerifier instead of Accurest.
Change that affects stubs resolution: https://github.com/spring-cloud/spring-cloud-contract/issues/54
> Weakening subs repository layout restrictions

- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/custom/ResponseRethrowingErrorHandler.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/custom/RestTemplate.groovy
- micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/ServiceRestClientConfigurationSupport.groovy
Reasoning for this change is two-fold:
1. in many situations, when using ServiceRestClient in catch clause usually first thing to do is log exception on error message - which in most cases just doubles the error message that was already logged by default ResponseRethrowingErrorHandler
2. there are situations where receiving 4xx response is expected behaviour - in that case logging error message result in confusion, since developer seeing error message in logs might assumes that something broke
Not wanting to change the default behaviour of this handler I think it's best to make it configurable and let the developers decide.
> configurable logging or ServiceRestClient error responses

- micro-infra-spring-config/build.gradle
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/LogbackConfigurationSpec.groovy
- micro-infra-spring-config/src/test/groovy/com/ofg/infrastructure/property/PropertiesFolderFinderSpec.groovy
When `CONFIG_FOLDER` property is set in the system (for example in `~/.bashrc`) or passed via `-D` some tests are failing. Few of them silently assumed that this property is not set.
> Fix for CONFIG_FOLDER property tests when set in environment

- build.gradle
- micro-deps/build.gradle
- stub-runner/stub-runner/build.gradle
SpringBoot 1.5.x plugin automatically applies dependency-management plugin which imports BOM `org.springframework.boot:spring-boot-dependencies`.
This forces WireMock to use resolved Jetty version which is 9.4.x (see [jetty.version](https://search.maven.org/remotecontent?filepath=org/springframework/boot/spring-boot-dependencies/1.5.9.RELEASE/spring-boot-dependencies-1.5.9.RELEASE.pom)), but WireMock is not ready for that. It supports Jetty 9.2.x.
Tom Akehurst suggests to use `wiremock-standalone` artifact which contains Jetty with appropriate version inside. See https://github.com/tomakehurst/wiremock/issues/644 and https://github.com/tomakehurst/wiremock/issues/551.
> Bumping WireMock to 2.13.0 Standalone

- micro-infra-spring-swagger/src/main/java/com/ofg/infrastructure/web/swagger/SwaggerConfiguration.java
At the bottom of swagger-ui.html there's an validation error:
```
Can't read from file http://<app_url>/v2/api-docs
```
returned by: `https://online.swagger.io/validator/debug?url=http://<app_url>/v2/api-docs`.
> Disabling validation of /v2/api-docs output

- build.gradle
Bumping versions:
* Spring Cloud Edgware.SR2
* CGLib 3.2.6
* RestAssured 3.0.7
* Wiremock 2.15.0
* SystemRules 1.17.1
* Jansi 1.17
> Spring Cloud Edgware.SR2 + others
